#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

DMENU_PATH="$HOME/bin:$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"

IFS=:
if stest -dqr -n "$cache" $DMENU_PATH; then
	stest -flx $DMENU_PATH | sort -u | tee "$cache"
else
	cat "$cache"
fi
